apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-final-fix
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'node-exporter'  # Názov, ktorý dashboard 1860 miluje
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_label_app]
            regex: 'node-exporter'
            action: keep
      - job_name: 'nginx-ingress-controller'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
