global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['10.156.15.199:9100']

  - job_name: 'nginx-ingress-controller'
    static_configs:
      - targets: ['ingress-nginx-controller-metrics.ingress-nginx.svc.cluster.local:10254']

rule_files:
  - "/etc/prometheus/rules/*.yml"
